### ISSUE TITLE
incase someone looking for YAML Config (SSH Command)

### ISSUE THREAD

**Issue by deepaksp** [maddox/actions#14]
hi, thank you for this action. now i dont need to login to server to pull latest repo

here is yaml config

`
name: Run SSH Command

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update Server Repo
      uses: maddox/actions/ssh@master
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      with:
        args: git pull or any code you want to run
`
Note - you can add more options please refer yaml config documentations

**Comment by Chathula** [comment]
@deepaksp , how to generate private key?

**Comment by DannyHinshaw** [comment]
Quick reformat for future peeps.

```yaml
      - name: Update Server Repo
        uses: maddox/actions/ssh@master
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        with:
          args: git pull
```

**Comment by mrdeds** [comment]
That solution seems to not be working.
Here's my `.yml`

```
name: deploy

on: 
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update Server Repo
      uses: maddox/actions/ssh@master
      env:
        PRIVATE_KEY: ${{ secrets.APOLLO_KEY }}
        HOST: ${{ secrets.APOLLO_HOST }}
        USER: ${{ secrets.APOLLO_USER }}
      with:
        args: git pull
```
I get this error:

```
Agent pid 12
Error loading key "/github/home/.ssh/deploy_key": invalid format
##[error]Docker run failed with exit code 1
```
