### ISSUE TITLE
Build faiks with enter passphrase for private key

### ISSUE THREAD

**Issue by abhisheksoni27** [maddox/actions#17]
/usr/bin/docker run --name bb8170d7fc42bc4d49f0b0a9f5bfdb63dcef_8d80bd --label 04bb81 --workdir /github/workspace --rm -e PRIVATE_KEY -e HOST -e USER -e INPUT_ARGS -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/api-tinyfold/api-tinyfold":"/github/workspace" 04bb81:70d7fc42bc4d49f0b0a9f5bfdb63dcef whoami
Agent pid 12
Enter passphrase for /github/home/.ssh/deploy_key: 
##[error]Docker run failed with exit code 1

**Comment by abhisheksoni27** [comment]
Should I be using a key without a passphrase?

**Comment by fatihyildizhan** [comment]
I am getting the same error.

The .yml file is like this:

```
name: SSH-Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and deploy node app
      uses: "maddox/actions/ssh@master"
      with:
        args: > 
          --host ${{ secrets.HOST }} --user ${{ secrets.SSH_USER }} --private_key ${{ secrets.SSH_KEY }}
          --script 'whoami'
```

```
Agent pid 13
Error loading key "/github/home/.ssh/deploy_key": invalid format
##[error]Docker run failed with exit code 1
```
